#include <Config/Settings/AlignSysMemSurfaces.h>
#include <Config/Settings/AlternatePixelCenter.h>
#include <Config/Settings/AltTabFix.h>
#include <Config/Settings/Antialiasing.h>
#include <Config/Settings/BltFilter.h>
#include <Config/Settings/ColorKeyMethod.h>
#include <Config/Settings/ConfigHotKey.h>
#include <Config/Settings/CpuAffinity.h>
#include <Config/Settings/CpuAffinityRotation.h>
#include <Config/Settings/DepthFormat.h>
#include <Config/Settings/DesktopColorDepth.h>
#include <Config/Settings/DesktopResolution.h>
#include <Config/Settings/DisplayAspectRatio.h>
#include <Config/Settings/DisplayFilter.h>
#include <Config/Settings/DisplayRefreshRate.h>
#include <Config/Settings/DisplayResolution.h>
#include <Config/Settings/DpiAwareness.h>
#include <Config/Settings/FontAntialiasing.h>
#include <Config/Settings/ForceD3D9On12.h>
#include <Config/Settings/FpsLimiter.h>
#include <Config/Settings/FullscreenMode.h>
#include <Config/Settings/LogLevel.h>
#include <Config/Settings/PalettizedTextures.h>
#include <Config/Settings/RemoveBorders.h>
#include <Config/Settings/RenderColorDepth.h>
#include <Config/Settings/ResolutionScale.h>
#include <Config/Settings/ResolutionScaleFilter.h>
#include <Config/Settings/SoftwareDevice.h>
#include <Config/Settings/SpriteDetection.h>
#include <Config/Settings/SpriteFilter.h>
#include <Config/Settings/SpriteTexCoord.h>
#include <Config/Settings/StatsColumns.h>
#include <Config/Settings/StatsHotKey.h>
#include <Config/Settings/SupportedResolutions.h>
#include <Config/Settings/SupportedDepthFormats.h>
#include <Config/Settings/SupportedTextureFormats.h>
#include <Config/Settings/TerminateHotKey.h>
#include <Config/Settings/TextureFilter.h>
#include <Config/Settings/ThreadPriorityBoost.h>
#include <Config/Settings/VertexBufferMemoryType.h>
#include <Config/Settings/VSync.h>
#include <Config/Settings/WinVersionLie.h>

namespace Config
{
	Settings::AlignSysMemSurfaces alignSysMemSurfaces;
	Settings::AlternatePixelCenter alternatePixelCenter;
	Settings::AltTabFix altTabFix;
	Settings::Antialiasing antialiasing;
	Settings::BltFilter bltFilter;
	Settings::ColorKeyMethod colorKeyMethod;
	Settings::ConfigHotKey configHotKey;
	Settings::CpuAffinity cpuAffinity;
	Settings::CpuAffinityRotation cpuAffinityRotation;
	Settings::DepthFormat depthFormat;
	Settings::DisplayAspectRatio displayAspectRatio;
	Settings::DesktopColorDepth desktopColorDepth;
	Settings::DesktopResolution desktopResolution;
	Settings::DisplayFilter displayFilter;
	Settings::DisplayRefreshRate displayRefreshRate;
	Settings::DisplayResolution displayResolution;
	Settings::DpiAwareness dpiAwareness;
	Settings::FontAntialiasing fontAntialiasing;
	Settings::ForceD3D9On12 forceD3D9On12;
	Settings::FpsLimiter fpsLimiter;
	Settings::FullscreenMode fullscreenMode;
	Settings::LogLevel logLevel;
	Settings::PalettizedTextures palettizedTextures;
	Settings::RemoveBorders removeBorders;
	Settings::RenderColorDepth renderColorDepth;
	Settings::ResolutionScale resolutionScale;
	Settings::ResolutionScaleFilter resolutionScaleFilter;
	Settings::SoftwareDevice softwareDevice;
	Settings::SpriteDetection spriteDetection;
	Settings::SpriteFilter spriteFilter;
	Settings::SpriteTexCoord spriteTexCoord;
	Settings::StatsColumns statsColumns;
	Settings::StatsHotKey statsHotKey;
	Settings::SupportedResolutions supportedResolutions;
	Settings::SupportedDepthFormats supportedDepthFormats;
	Settings::SupportedTextureFormats supportedTextureFormats;
	Settings::TerminateHotKey terminateHotKey;
	Settings::TextureFilter textureFilter;
	Settings::ThreadPriorityBoost threadPriorityBoost;
	Settings::VertexBufferMemoryType vertexBufferMemoryType;
	Settings::VSync vSync;
	Settings::WinVersionLie winVersionLie;
}
